modLoader="javafml" #mandatory
	
loaderVersion="[37,)" #mandatory 

license="All rights reserved"

[[mods]] #mandatory
	
modId="nero" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Nero" #mandatory

logoFile="" #optional

credits="Thanks for downloading my Mod" #optional
	
authors="Luis" #optional

description='''
// TODO: add description
'''
	
[[dependencies.nero]] #optional
	
    modId="forge" #mandatory
    
    mandatory=true #mandatory
    
    versionRange="[37,)" #mandatory
    
    ordering="NONE"
    
    side="BOTH"
    
[[dependencies.nero]]
		
    modId="minecraft"
    
    mandatory=true

    versionRange="[1.17.1,1.18)"
    
    ordering="NONE"
    
    side="BOTH"