modLoader="javafml" #mandatory
	
loaderVersion="[37,)" #mandatory 

license="All rights reserved"

[[mods]] #mandatory
	
modId="nero" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Nero" #mandatory

logoFile="" #optional

credits="Thanks for downloading my Mod" #optional
	
authors="Luis" #optional

description='''
Nero adds a lot of cool new Features, 
 - One of the most interesting ones is the custom Dimension called Deepslate
 - Another feature is the Blood Magic System which is remake from 1.8

One last thing which is very important, have a lot of fun when playing
Nero Development Team
'''
	
[[dependencies.nero]] #optional
	
    modId="forge" #mandatory
    
    mandatory=true #mandatory
    
    versionRange="[37,)" #mandatory
    
    ordering="NONE"
    
    side="BOTH"
    
[[dependencies.nero]]
		
    modId="minecraft"
    
    mandatory=true

    versionRange="[1.17.1,1.18)"
    
    ordering="NONE"
    
    side="BOTH"